limit_req_zone $binary_remote_addr zone=login:10m rate=300r/m;
limit_conn_zone $binary_remote_addr zone=per_ip:10m;

server {
    listen 80 default_server;
    server_name _;
    server_tokens off;
    include /etc/nginx/snippets/app.conf;
}
